import { Link, useParams } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const pages = {
  about: ["Our story", "Food that fits your day.", "FoodExpress connects hungry customers with local restaurants and delivery partners. Our goal is simple: make finding and enjoying great local food feel effortless.", ["Discover restaurants and menus in one place.", "Get clear order updates from checkout to delivery.", "Support local food businesses in your neighbourhood."], ["Browse restaurants", "/restaurants"]],
  careers: ["Careers", "Build better food moments.", "We welcome practical, customer-focused people across operations, partnerships, support and product.", ["Email careers@foodexpress.in with your résumé and preferred role.", "Tell us about the customer problem you would like to solve.", "We value ownership, kindness and continuous learning."], ["Contact our team", "/contact"]],
  blog: ["FoodExpress journal", "Ideas for better ordering.", "Our journal shares useful tips for choosing meals, discovering cuisines and supporting local restaurants.", ["Save favourites to make repeat orders quicker.", "Use cuisine filters to discover something new.", "Check menu descriptions for ingredients and portions."], ["Explore restaurants", "/restaurants"]],
  press: ["Press room", "FoodExpress in the news.", "For company information, product updates or interview requests, our communications team is ready to help.", ["Media enquiries: press@foodexpress.in.", "Include your publication and deadline in your request.", "Please request approval before using FoodExpress brand assets."], ["Contact us", "/contact"]],
  contact: ["Contact", "We are here to help.", "Choose the right contact channel and include an order number whenever you are asking about a specific order.", ["Customer support: support@foodexpress.in.", "Restaurant partnerships: partners@foodexpress.in.", "General enquiries: hello@foodexpress.in."], ["Get support", "/support"]],
  terms: ["Legal", "Terms of service.", "These terms set out the basic rules for using FoodExpress and placing orders through the platform.", ["Keep your account information accurate and secure.", "Review restaurant, items, address and total before confirming an order.", "Cancellation options depend on order preparation status."], ["Privacy policy", "/privacy"]],
  cuisines: ["Explore food", "Popular cuisines, one place.", "Find familiar favourites or try something different from restaurants near you.", ["North Indian, South Indian, Chinese and fast food.", "Pizza, burgers, biryani, rolls and desserts.", "Use search to find a dish or restaurant quickly."], ["Browse restaurants", "/restaurants"]],
  offers: ["Offers", "Make every order count.", "Available offers can vary by restaurant, location and time. Your final saving is shown before you pay.", ["Look for offer details on restaurant and menu pages.", "Check the minimum order value before applying an offer.", "Only eligible offers are applied at checkout."], ["Find restaurants", "/restaurants"]],
  support: ["Help centre", "Support when you need it.", "Get help with order status, payment questions, delivery issues and account access.", ["Open My orders to see the latest status for an order.", "Check your order details before reporting a payment concern.", "Email support@foodexpress.in with your order number if you need help."], ["View my orders", "/orders"]],
  faqs: ["Frequently asked questions", "Quick answers.", "Useful answers for common questions before and after placing an order.", ["Track an order from the My orders page.", "Manage saved delivery addresses from your account.", "Order details include items, payment total and delivery address."], ["Manage addresses", "/addresses"]],
  "restaurant-partner": ["For restaurants", "Grow with FoodExpress.", "Partner with us to make your menu discoverable to more local customers.", ["Share restaurant details, your menu and service area.", "Keep availability and preparation times current.", "Email partners@foodexpress.in to start a conversation."], ["Partner resources", "/restaurant-resources"]],
  "restaurant-app": ["Restaurant tools", "Your restaurant, in control.", "The Restaurant App helps partner teams manage orders and menu availability.", ["Review and confirm incoming orders promptly.", "Mark unavailable dishes quickly to avoid substitutions.", "Contact partners@foodexpress.in for restaurant support."], ["See pricing", "/restaurant-pricing"]],
  "restaurant-resources": ["Restaurant resources", "Tools for great service.", "Small operating habits can make ordering clearer for customers and shifts smoother for restaurant teams.", ["Use clear dish names and accurate descriptions.", "Set realistic preparation times during peak hours.", "Pack and label every order carefully before handoff."], ["Become a partner", "/restaurant-partner"]],
  "restaurant-pricing": ["Restaurant pricing", "A straightforward partnership.", "Commercial terms are discussed based on restaurant type, location and operational needs.", ["We discuss service area and menu setup requirements.", "Review all terms before accepting a partnership.", "Request a proposal at partners@foodexpress.in."], ["Contact partnerships", "/contact"]],
  "restaurant-stories": ["Partner stories", "Local food, stronger together.", "The most successful restaurant partnerships focus on a great menu and reliable customer experience.", ["Accurate menus help diners order with confidence.", "Reliable preparation times encourage repeat orders.", "Careful handoffs support a better delivery experience."], ["Join as a partner", "/restaurant-partner"]],
  "delivery-partner": ["For delivery partners", "Deliver on your schedule.", "Delivery partners help bring local food to customers while staying connected through the app.", ["Tell us your city at delivery@foodexpress.in.", "Review pickup and delivery instructions before accepting an order.", "Follow local safety and traffic rules at every step."], ["See requirements", "/delivery-requirements"]],
  "delivery-app": ["Delivery tools", "Stay ready for every drop.", "The Delivery Partner App provides assigned-order information and delivery updates.", ["Review pickup, drop-off and customer instructions.", "Keep location services enabled while delivering where available.", "Do not use the app while riding or driving; stop safely first."], ["Partner benefits", "/delivery-benefits"]],
  "delivery-benefits": ["Partner benefits", "Flexible work, local impact.", "Delivery partners are essential to a reliable customer experience and local restaurant growth.", ["Choose availability that works with your schedule, subject to local demand.", "Receive clear pickup and drop-off details for assigned orders.", "Help customers enjoy food from neighbourhood restaurants."], ["Become a partner", "/delivery-partner"]],
  "delivery-requirements": ["Before you join", "Delivery partner requirements.", "Requirements may differ by city, but each partner must meet applicable legal and safety expectations.", ["A smartphone, reliable phone number and identity document are essential.", "Use a safe, legally compliant way to complete deliveries.", "Follow traffic rules and handle food with care."], ["Start a partnership", "/delivery-partner"]],
  privacy: ["Legal", "Privacy policy.", "We use information needed to process orders, communicate updates, prevent misuse and provide support.", ["We use account, delivery, order and support information you provide.", "You can review account information from your profile.", "Contact support with privacy questions or requests."], ["Contact support", "/support"]],
  "content-policy": ["Legal", "Content policies.", "FoodExpress content should be accurate, respectful and useful to customers, restaurants and delivery partners.", ["Restaurant menus, prices and availability must be current.", "Reviews and messages should be honest and respectful.", "We may remove content that is misleading, unsafe or abusive."], ["Read terms", "/terms"]],
};

export default function FooterInfoPage() {
  const { page } = useParams();
  const [kicker, title, intro, points, action] = pages[page] || pages.about;
  return <><Navbar /><main className="page-shell py-10 sm:py-16"><section className="rounded-[2rem] bg-slate-900 px-6 py-12 text-white sm:px-12"><p className="text-sm font-bold uppercase tracking-[.2em] text-orange-300">{kicker}</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">{intro}</p></section><section className="mt-8 grid gap-5 md:grid-cols-3">{points.map((point, index) => <article key={point} className="soft-card p-6"><p className="text-sm font-bold uppercase tracking-wider text-orange-600">{`0${index + 1}`}</p><p className="mt-3 leading-7 text-slate-700">{point}</p></article>)}</section><Link to={action[1]} className="mt-8 inline-flex rounded-xl bg-orange-500 px-5 py-3 font-bold text-white shadow-lg shadow-orange-200 hover:bg-orange-600">{action[0]}</Link></main><Footer /></>;
}
